kind: pipeline
name: check-same-code-base

steps:
  - name: check-same-code-base
    image: nextcloudci/php8.0:php8.0-1
    commands:
      - make check-same-code-base

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: php72-cli

steps:
  - name: php72-cli
    image: nextcloudci/php7.2:php7.2-14
    commands:
      - make test-cli

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: php73-cli

steps:
  - name: php73-cli
    image: nextcloudci/php7.3:php7.3-5
    commands:
      - make test-cli

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: php74-cli

steps:
  - name: php74-cli
    image: nextcloudci/php7.4:php7.4-3
    commands:
      - make test-cli

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: php72-stable19

steps:
  - name: php72-stable19
    image: nextcloudci/php7.2:php7.2-14
    commands:
      - make test-stable19

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: php73-stable19

steps:
  - name: php73-stable19
    image: nextcloudci/php7.3:php7.3-5
    commands:
      - make test-stable19

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: php74-stable19

steps:
  - name: php74-stable19
    image: nextcloudci/php7.4:php7.4-3
    commands:
      - make test-stable19

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: php73-stable20

steps:
  - name: php73-stable20
    image: nextcloudci/php7.3:php7.3-5
    commands:
      - make test-stable20

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: php74-stable20

steps:
  - name: php74-stable20
    image: nextcloudci/php7.4:php7.4-3
    commands:
      - make test-stable20

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: php71-stable16

steps:
  - name: php71-stable16
    image: nextcloudci/php7.1:php7.1-16
    commands:
      - make test-stable16

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: php72-stable16

steps:
  - name: php72-stable16
    image: nextcloudci/php7.2:php7.2-12
    commands:
      - make test-stable16

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: php73-stable16

steps:
  - name: php73-stable16
    image: nextcloudci/php7.3:php7.3-2
    commands:
      - make test-stable16

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push

---
kind: pipeline
name: php73-master

steps:
  - name: php73-master
    image: nextcloudci/php7.3:php7.3-2
    commands:
      - make test-master

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push
---
kind: pipeline
name: php74-master

steps:
  - name: php74-master
    image: nextcloudci/php7.4:php7.4-2
    commands:
      - make test-master

trigger:
  branch:
    - master
    - stable*
  event:
    - pull_request
    - push
