# SPDX-FileCopyrightText: 2022 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: MIT
name: Test cli

on:
  pull_request:
  push:
    branches:
      - main
      - master
      - stable*

permissions:
  contents: read

concurrency:
  group: updater-test-cli-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test-cli:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ["8.2"]

    name: test-cli

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up php ${{ matrix.php-versions }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: apcu,ctype,curl,dom,fileinfo,ftp,gd,intl,json,ldap,mbstring,openssl,pdo_sqlite,posix,sqlite,xml,zip
          coverage: none
          ini-file: development

      - name: Install dependencies
        run: composer i

      - name: test-cli
        run: make test-cli
